# Generated by Django 3.0.7 on 2020-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200703_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2122, upload_to='media'),
            preserve_default=False,
        ),
    ]
